### ISSUE TITLE
Medium script does not remove privacy/cookie popup

### ISSUE THREAD

**Issue by matejdro** [dylanarmstrong/userscripts#1]
Even with the script installed, this popup appears from time to time:

![image](https://user-images.githubusercontent.com/507922/63569808-2d1c7600-c57b-11e9-9b16-81e5fdf0c280.png)

**Comment by dylanarmstrong** [comment]
Hey @matejdro, thanks for the bug report. I pushed an update that removes the EU banner, let me know if that fixes your issue and I'll close this.

**Comment by matejdro** [comment]
It appears to work. Thanks for the quick fix!
